---
title: "adventofcode"
author: "ahermanski"
date: "1 12 2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

Türchen Nummer 1

Stern 1

```{r}
zahlen <- read_csv("input_tag1.csv", col_names = c("expenses"))
```

```{r}
expand_grid(zahlen, zahlen, .name_repair = "minimal") %>% 
  janitor::clean_names() %>% 
  mutate(summe = expenses + expenses_2) %>% 
  filter(summe == 2020) %>% 
  mutate(product = expenses * expenses_2)
```

Stern 2

```{r}
expand_grid(zahlen, zahlen, zahlen, .name_repair = "minimal") %>% 
  janitor::clean_names() %>% 
  mutate(summe = expenses + expenses_2 + expenses_3) %>% 
  filter(summe == 2020) %>% 
  mutate(product = expenses * expenses_2 * expenses_3)
```

```{r}
zahlen2 = pull(zahlen)

expand_grid(x = zahlen2, y = zahlen2, z = zahlen2) %>% 
  mutate(summe = x + y + z) %>% 
  filter(summe == 2020) %>% 
  mutate(produkt = x * y * z)
```

Türchen Nummer 2

```{r}
input <- read_csv("input_tag2.csv", col_names = c("passw"))
```

```{r}
input %>% 
  separate(passw, into = c("a", "b", "c"), sep = "\\s") %>% 
  separate(a, into = c("l", "u")) %>% 
  mutate(l = as.integer(l), u = as.integer(u), b = str_remove(b, ":")) %>% 
  mutate(count = str_count(c, b)) %>% 
  filter(!count < l & !count > u)
```

Stern 2

```{r}
input %>% 
  separate(passw, into = c("a", "b", "c"), sep = "\\s") %>% 
  separate(a, into = c("l", "u")) %>% 
  mutate(l = as.integer(l), u = as.integer(u), b = str_remove(b, ":")) %>% 
  mutate(pos1 = str_sub(c, l, l), pos2 = str_sub(c, u, u)) %>% 
  mutate(valid = (pos1 != pos2 & (b == pos1 | b == pos2))) %>% 
  filter(valid == TRUE) 
```

Türchen Nummer 3

```{r}
input_tag3 <- read_table2("input_tag3.txt", 
    col_names = c("a"))
```

Stern 1

```{r}
input_tag3 %>% 
  mutate(b = str_dup(a, 32)) %>% 
  unite(a, b) %>% 
  mutate(b = str_length(string = a)) %>% 
  mutate(c = seq(1, 969, 3), c = as.integer(c)) %>% 
  mutate(d = substring(a, c, c)) %>% 
  mutate(e = str_count(d, "#")) %>% 
  summarise(summe = sum(e))
```

Stern 2

```{r}
slope <- function(x, y, z) {
  input_tag3 %>% 
    mutate(b = str_dup(a, ceiling(nrow(input_tag3)*x/31))) %>% 
    unite(a, b) %>% 
    slice(which(row_number() %% y == z)) %>% 
    mutate(b = str_length(string = a)) %>% 
    mutate(c = seq(1, ceiling(nrow(input_tag3) / y) * x, x), c = as.integer(c)) %>% 
    mutate(d = substring(a, c,c)) %>% 
    mutate(e = str_count(d, "#")) %>% 
    summarise(summe = sum(e)) %>% 
    pull(summe)
}
```

```{r}
rows <- tibble(x = c(1, 3, 5, 7, 1), y = c(1, 1, 1, 1, 2), z = c(0, 0, 0, 0, 1))

rows %>% 
  rowwise() %>% 
  mutate(Ergebnis = slope(x, y, z)) %>% 
  tibble() %>% 
  summarise(Ergebnis = prod(Ergebnis))
```

Türchen Nummer 4

Stern 1

https://www.reddit.com/r/adventofcode/comments/k6e8sw/2020_day_04_solutions/gel0ikl/

or https://twitter.com/drob/status/1334729681812267008

```{r}
input_tag4 <- tibble(pass = readLines("input_tag4.txt")) 
```

```{r}
req <- c("byr", "iyr", "eyr", "hgt", "hcl", "ecl", "pid")

gültig <- input_tag4 %>% 
  mutate(id = cumsum(pass == "")) %>% 
  filter(pass != "") %>% 
  group_by(id) %>% 
  summarise(pass = paste(pass, collapse = " ")) %>% 
  mutate(pass = str_split(pass, " ")) %>% 
  unnest(pass) %>% 
  separate(pass, into = c("schlüssel", "wert"), sep = ":") %>% 
  group_by(id) %>% 
  filter(all(req %in% c(schlüssel))) %>% 
  pivot_wider(names_from = schlüssel, values_from = wert)

gültig
```

Stern 2

```{r}
gültig %>% 
  select(8,2,5, everything()) %>% 
  mutate(across(ends_with("yr"), as.integer)) %>% 
  filter(byr >1919 & 2004 > byr, iyr > 2009 & 2021 > iyr, between(eyr, 2020, 2030),
         (str_detect(hgt, "cm") & between(parse_number(hgt), 150, 193)) | 
            (str_detect(hgt, "in") & between(parse_number(hgt), 59, 76)),
         str_detect(hcl, "^#[a-f0-9]{6}$"),
         ecl %in% c("amb", "blu", "brn", "gry", "grn", "hzl", "oth"),
         str_detect(pid, "^[0-9]{9}$")) %>% 
  nrow()
```

Türchen Nummer 5

```{r}
x <- vector(length = 128)

x <- c(0:127)

fancycut(x, buckets = 10)

reihen = 128

x <- c(0:(reihen-1))

[1:64]


x[5]
```

https://www.reddit.com/r/adventofcode/comments/k71h6r/2020_day_05_solutions/geoirl9/

```{r}
library(readr)
library(dplyr)
library(stringr)

read_lines(("input_tag5.txt")) %>%
  str_replace_all("B|R", "1") %>%
  str_replace_all("F|L", "0") %>%
  strtoi(base = 2) %>%
  as_tibble() %>%
  summarize(part1 = max(value),
  part2 = setdiff(min(value):max(value),value))
```

Türchen Nummer 6

Stern 1

```{r}
input_tag6 <- tibble(antworten = readLines("input_tag6.txt")) 
```
```{r}
input_tag6 %>% 
  mutate(gruppe = cumsum(antworten == ""))  %>% 
  filter(antworten != "") %>% 
  group_by(gruppe) %>% 
  summarise(antworten = paste(antworten, collapse = "")) %>% 
  mutate(antworten = str_split(antworten, "")) %>% 
  unnest(antworten) %>% 
  group_by(gruppe) %>% 
  summarise(antwort = (n_distinct(antworten))) %>% 
  summarise(antwort = sum(antwort))
```

Stern 2

Lösung 1 (Die mal funktionierte)

```{r}
input_tag6 %>% 
  mutate(gruppe = cumsum(antworten == ""))  %>% 
  filter(antworten != "") %>% 
  group_by(gruppe) %>% 
  mutate(mitglied = row_number()) %>% 
  group_by(gruppe, mitglied) %>% 
  mutate(buchstaben = str_split(antworten, "")) %>% 
  unnest(buchstaben)  %>% 
  group_by(gruppe, buchstaben) %>% 
  mutate(count = n()) %>% 
  group_by(gruppe) %>% 
  filter(max(mitglied) == count) %>% 
  group_by(gruppe) %>% 
  # summarise(gemeinsam = paste(buchstaben, collapse = "")) 
  mutate(anzahl = n_distinct(buchstaben)) 
  summarise(anzahl = sum(distinct(anzahl)))
```

Lösung 2

```{r}
input_tag6 %>% 
  mutate(gruppe = cumsum(antworten == ""))  %>% 
  filter(antworten != "") %>% 
  group_by(gruppe) %>% 
  mutate(mitglied = row_number()) %>% 
  group_by(gruppe, mitglied) %>% 
  mutate(buchstaben = str_split(antworten, "")) %>% 
  unnest(buchstaben)  %>% 
  group_by(gruppe, buchstaben) %>% 
  mutate(count = n()) %>% 
  group_by(gruppe) %>% 
  filter(max(mitglied) == count) %>% 
  group_by(gruppe, mitglied) %>% 
  summarise(gemeinsam = paste(buchstaben, collapse = "")) %>% 
  slice(1) %>% 
  mutate(anzahl = str_length(gemeinsam)) %>% 
  ungroup() %>% 
  summarise(anzahlen = sum(anzahl))
```
https://twitter.com/drob/status/1335453278558167040

```{r}
input <- tibble(x = readLines("input_tag6.txt"))

 input %>% 
  mutate(group = cumsum(x=="")) %>% 
  filter(x != "") %>% 
  add_count(group, name = "group_total") %>% 
  separate_rows(x, sep = "") %>% 
  filter(x !="") %>% 
  distinct(group,x)
 
 
  input %>% 
  mutate(group = cumsum(x=="")) %>% 
  filter(x != "") %>% 
  add_count(group, name = "group_total") %>% 
  separate_rows(x, sep = "") %>% 
  filter(x !="") %>% 
  count(group, x, group_total) %>% 
  filter(n == group_total)
```


